SELECT CLIENT_NAME FROM CLIENT_MASTER;
SELECT * FROM CLIENT_MASTER;	
SELECT CLIENT_NAME,CITY,STATE FROM CLIENT_MASTER;
SELECT PRODUCT_DESCRIPTION FROM PRODUCT_MASTER;
SELECT CLIENT_NAME,CITY FROM CLIENT_MASTER
WHERE CITY = "MUMBAI";
SELECT SALESMANNAME,SALAMT FROM SALESMAN_MASTER
WHERE SALAMT = 3000;

UPDATE CLIENT_MASTER
SET CITY = "Banglore"
WHERE CLIENT_NO = "C00005";

SET SQL_SAFE_UPDATES=0;

UPDATE CLIENT_MASTER
SET BALDUE = 1000
WHERE CLIENT_NO = "C00001";

UPDATE PRODUCT_MASTER
SET COSTPRICE = 950
WHERE PRODUCT_DESCRIPTION = "Trousers";

UPDATE SALESMAN_MASTER
SET CITY = "Pune";

DELETE FROM SALESMAN_MASTER
WHERE SALAMT = 3500;

DELETE FROM PRODUCT_MASTER
WHERE QTYONHAND = 100;

DELETE FROM CLIENT_MASTER
WHERE STATE = "Tamil Nadu";

ALTER TABLE CLIENT_MASTER 
ADD TELEPHONE_NO BIGINT ;

ALTER TABLE PRODUCT_MASTER 
MODIFY SELLPRICE Decimal (10,2) ;

DROP TABLE CLIENT_MASTER;

ALTER TABLE SALESMAN_MASTER 
RENAME TO sman_mast;
RENAME TO sman_mast;